// Mocks generated by Mockito 5.4.6 from annotations
// in realview_task/test/unit/repository/default_books_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:multiple_result/multiple_result.dart' as _i4;
import 'package:realview_task/feature/data/datasource/books_api_client.dart'
    as _i2;
import 'package:realview_task/feature/data/model/authors_response.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BooksApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockBooksApiClient extends _i1.Mock implements _i2.BooksApiClient {
  MockBooksApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.AuthorsResponse, Exception>> getAuthorsByQuery(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthorsByQuery, [query]),
            returnValue:
                _i3.Future<_i4.Result<_i5.AuthorsResponse, Exception>>.value(
                  _i6.dummyValue<_i4.Result<_i5.AuthorsResponse, Exception>>(
                    this,
                    Invocation.method(#getAuthorsByQuery, [query]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.AuthorsResponse, Exception>>);
}
